### ISSUE TITLE
formated numbers for performance measure when visualizing them. 

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/open-eval#123]
Let's strip numbers so that they are no very long; like showing two digits after the decimal point. 
<img width="234" alt="screen shot 2016-03-15 at 5 20 16 pm" src="https://cloud.githubusercontent.com/assets/2441454/13796226/89d2eaae-ead3-11e5-91da-0efbdc0fc90f.png">

**Comment by paultgibbons** [comment]
this one is done too
