### ISSUE TITLE
No User Feedback when a Configuration Run ends

### ISSUE THREAD

**Issue by bhargav** [IllinoisCogComp/open-eval#206]
At the end of a configuration run, the page should refresh or go to the configuration details page. Right now it is just stuck at "60 out of 60 Text Annotations processed" with a "Stop Run" button.

**Comment by danyaljj** [comment]
Is it yours system?: 
<img width="624" alt="screen shot 2016-05-09 at 3 53 58 pm" src="https://cloud.githubusercontent.com/assets/2441454/15127884/5eb6860e-15fe-11e6-855e-4fa0c54c5bc0.png">
Looks like a network issue.

**Comment by bhargav** [comment]
Okay. I had a successful run where all 60 TA's were processed and I see results but the UI doesn't update to indicate that the run has ended.

**Comment by bhargav** [comment]
Invalid issue. Network issue.
